### ISSUE TITLE
Chip modification - adding 2 new colours 

### ISSUE THREAD

**Issue by AustraAnna** [ebi-uniprot/franklin-sites#107]
**Chip**

**Description of the new modifier(s)**
addition of 2 new colour variations 966336 - "Coyote brown" and 374343 - "Outer space"

<img width="607" alt="Screenshot 2020-10-09 at 11 35 03" src="https://user-images.githubusercontent.com/72505072/95573537-84053900-0a23-11eb-9584-400785387896.png">
**Description of the new modifier(s) behaviour**
 the same as previously 

**Are the purpose and function of the component the same?**
the same as previously, just introduced 2 new colours

**Add Screenshots / Mockups**

**Comment by aurel-l** [comment]
Changes are now in, you can see it now at https://ebi-uniprot.github.io/franklin-sites/?path=/story/core-chip--chips
You should be able to change to any colour in the design system from the bottom panel
