### ISSUE TITLE
Add "Data visualisation" to Colour 

### ISSUE THREAD

**Issue by AustraAnna** [ebi-uniprot/franklin-sites#108]
**Name of component**
addition of a new title as one of the sub titles to the colour category  "Data visualisation" the names of the new colours  966336 - "Coyote brown" and 374343 - "Outer space" in this subcategory 

**Additional modifiers** 
Colour 

**Description of the component**
Would work similar as Primary, Grey, “Curation” (or “namespace”?) titles under the colour category,  just new additional section of the tile “Data visualisation” and 2 new colours 966336 - "Coyote brown" and 374343 - "Outer space"

**Description of the behaviour (including modifiers)**
Contrasting colours for data visualisation 

**Function**
Contrasting colours for data visualisation 

**Purpose** 
Contrasting colours to the primary and grey palette - differentiate and highlight data visual sections 

**Add any relevant screenshots/mockups**
<img width="607" alt="Screenshot 2020-10-09 at 11 35 03" src="https://user-images.githubusercontent.com/72505072/95606145-d6f5e500-0a51-11eb-8d3b-be52b726b789.png">

**Comment by aurel-l** [comment]
Changes are now in, new colours visible at https://ebi-uniprot.github.io/franklin-sites/?path=/story/core-colours--colours
