### ISSUE TITLE
Data info list compact

### ISSUE THREAD

**Issue by AustraAnna** [ebi-uniprot/franklin-sites#113]
**Name of component**
Data info list compact

**Component modifier**
Modification of the info list just more compact - and a replacement of the current "Data info list compact"

**Description of the change**
Replacement of current Data info list compact - adding a blue line on the left - the same as in the "Info list" - "Vivid Cerulean"  00A6D5

**Add Screenshots / Mockups if relevant**

![Screenshot 2020-10-16 at 16 50 59](https://user-images.githubusercontent.com/72505072/96280447-e20bc080-0fcf-11eb-9b1c-be1a5007ba85.png)

https://www.figma.com/file/ZZueKoah2DtCn9mFonbshf/Biocomponents?node-id=0%3A1

**Comment by xwatkins** [comment]
Change now live https://ebi-uniprot.github.io/franklin-sites/?path=/story/data-info-list--columns-compact
