### ISSUE TITLE
Colour Pumpkin 

### ISSUE THREAD

**Issue by AustraAnna** [ebi-uniprot/franklin-sites#118]
**Name of component**
New colour for UniRef section, "Pumpkin" F2994C

**Additional modifiers** 
Subsection in colours "Name space" update  - colour for UniRef "Pumpkin"  F2994C

**Description of the component**
"Pumpkin" F2994C used in UniRef header or related designs to indicate UniRef

**Description of the behaviour (including modifiers)**
Colour - needed or selected components are altered to "Pumpkin" once user is on UniRef pages

**Function**
Indicate the user that is landed on UniRef pages

**Purpose** 
Cohesive style element from home page to UniRef landing page

**Add any relevant screenshots/mockups**
![Screenshot 2020-10-27 at 15 07 58](https://user-images.githubusercontent.com/72505072/97320973-49dec880-1866-11eb-96f8-b769d00c6e8e.png)
![Screenshot 2020-10-27 at 15 08 15](https://user-images.githubusercontent.com/72505072/97320987-4d724f80-1866-11eb-8941-dabc6b8d1f5e.png)
![Screenshot 2020-10-27 at 15 07 43](https://user-images.githubusercontent.com/72505072/97321001-506d4000-1866-11eb-919f-d1907a44bb94.png)

**Comment by aurel-l** [comment]
handled in #122
