### ISSUE TITLE
New colour "Green tea"

### ISSUE THREAD

**Issue by AustraAnna** [ebi-uniprot/franklin-sites#123]
**Name of component**
New colour "Green tea"  88C19D 

**Description of the new modifier(s)**
Colour to be used as identifier for UniParc to be added in Franklin colour section 

**Description of the new modifier(s) behaviour**
Colour

**Are the purpose and function of the component the same?**
colour for UniParc

**Add Screenshots / Mockups**

![Screenshot 2020-11-09 at 13 54 26](https://user-images.githubusercontent.com/72505072/98549715-1bfc7980-2293-11eb-9d8b-e8576d6e80cf.png)

**Comment by aurel-l** [comment]
handled in #122
