### ISSUE TITLE
Evedence tag

### ISSUE THREAD

**Issue by AustraAnna** [ebi-uniprot/franklin-sites#188]
**Name of component**
Evidence tag

**Component modifier**
evidence tag, mouse over and "pressed", "selected"

**Description of the change**
Colour overlapping with other design areas - regular - fill Gainsboro stroke Weldon Blue, mouse over - fill Pastel blue, stroke Weldon Blue, "pressed" - fill Independence 70 %, stroke Weldon Blue

**Add Screenshots / Mockups if relevant**

![Screenshot 2021-04-29 at 17 31 29](https://user-images.githubusercontent.com/72505072/116585900-c2573c80-a910-11eb-8cf3-42eb6038a55b.png)

https://www.figma.com/file/D2euYJHUDqsu4m1SqfWl6p/Help?node-id=808%3A4068

**Comment by xwatkins** [comment]
Done
